# MedMemo 赞助渠道
# 详见：https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# github: [hzhan516]      # 如有 GitHub Sponsors 账号，取消注释
# patreon: # 你的 Patreon 用户名
# open_collective: # 你的 Open Collective 名称
# ko_fi: # 你的 Ko-fi 用户名
# custom: # 自定义赞助链接
