version: 2
project_name: MedMemo

before:
  hooks:
    - bash -c 'cd web && npm ci && npm run build'

builds:
  - skip: true

checksum:
  name_template: 'checksums.txt'

release:
  draft: true
  prerelease: auto
  mode: append
  name_template: "MedMemo {{ .Version }}"
  extra_files:
    - glob: build/bin/*.AppImage
    - glob: build/bin/*.dmg
    - glob: build/bin/*-installer.exe

changelog:
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
