// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/hzhan516/medmemo/internal/adapters/ai"
	"github.com/hzhan516/medmemo/internal/adapters/auth"
	"github.com/hzhan516/medmemo/internal/adapters/detector"
	"github.com/hzhan516/medmemo/internal/adapters/repository"
	"github.com/hzhan516/medmemo/internal/adapters/updater"
	"github.com/hzhan516/medmemo/internal/application/healthcheck"
	"github.com/hzhan516/medmemo/internal/application/pipeline"
	updater2 "github.com/hzhan516/medmemo/internal/application/updater"
	"github.com/hzhan516/medmemo/internal/application/usecase"
	"github.com/hzhan516/medmemo/internal/infrastructure/onnx"
	"github.com/hzhan516/medmemo/internal/infrastructure/secret"
	"github.com/hzhan516/medmemo/pkg/models"
	"strings"
)

import (
	_ "unsafe"
)

// Injectors from wire.go:

// InitializeApp 通过 Wire 编译期依赖注入组装完整应用。
// 返回 (func()) 作为资源清理回调，由 main 函数通过 defer 调用。
func InitializeApp() (*App, func(), error) {
	llmClientFactory := ai.NewLLMClientFactory()
	updateChannel := ProvideDefaultUpdateChannel()
	appConfig, err := NewAppConfig(updateChannel)
	if err != nil {
		return nil, nil, err
	}
	keyringStore, err := secret.NewKeyringStore()
	if err != nil {
		return nil, nil, err
	}
	sqlCipherConnector, err := NewSQLCipherConnectorFromConfig(appConfig, keyringStore)
	if err != nil {
		return nil, nil, err
	}
	providerRepoSQLite, err := repository.NewProviderRepoSQLite(sqlCipherConnector, keyringStore)
	if err != nil {
		return nil, nil, err
	}
	memoryRepoSQLite := repository.NewMemoryRepoSQLite(sqlCipherConnector)
	ruleDetector := detector.NewRuleDetector()
	ruleComplianceChecker, err := usecase.NewRuleComplianceChecker()
	if err != nil {
		return nil, nil, err
	}
	l1RuleStage := pipeline.NewL1RuleStage()
	engineConfig := NewEngineConfig(appConfig)
	engine, err := onnx.NewEngine(engineConfig)
	if err != nil {
		return nil, nil, err
	}
	onnxnerDetector := detector.NewONNXNERDetector(engine)
	l2NERStage := pipeline.NewL2NERStage(onnxnerDetector)
	deidentifyPipeline := pipeline.NewDefaultDeidentifyPipeline(l1RuleStage, l2NERStage)
	embeddingServiceAdapter := NewEmbeddingServiceAdapterWithVersion(engine)
	embeddingRepoSQLite := repository.NewEmbeddingRepoSQLite(sqlCipherConnector)
	factRepoSQLite := repository.NewFactRepoSQLite(sqlCipherConnector)
	decayScorer := usecase.NewDecayScorer()
	migrationState := usecase.NewMigrationState()
	queryExpansionService := usecase.NewQueryExpansionService()
	intentResolver := usecase.NewIntentResolver(queryExpansionService)
	memoryRetriever := usecase.NewMemoryRetriever(embeddingServiceAdapter, embeddingRepoSQLite, factRepoSQLite, memoryRepoSQLite, decayScorer, migrationState, intentResolver, queryExpansionService)
	confidenceAggregator := usecase.NewConfidenceAggregator()
	localAnswerConfig := usecase.NewLocalAnswerConfig()
	localAnswerService := usecase.NewLocalAnswerService(localAnswerConfig)
	accuracyRepoSQLite := repository.NewAccuracyRepoSQLite(sqlCipherConnector)
	accuracyService := usecase.NewAccuracyService(accuracyRepoSQLite)
	knowledgeRepoSQLite := repository.NewKnowledgeRepoSQLite(sqlCipherConnector)
	knowledgeTokenizer := usecase.NewKnowledgeTokenizer()
	knowledgeReranker := usecase.NewKnowledgeReranker()
	knowledgeSearchService := usecase.NewKnowledgeSearchService(knowledgeRepoSQLite, knowledgeTokenizer, embeddingServiceAdapter, knowledgeReranker)
	citationBuilder := usecase.NewCitationBuilder(knowledgeRepoSQLite)
	chatOrchestratorDeps := usecase.ChatOrchestratorDeps{
		LLMFactory:           llmClientFactory,
		ProviderStore:        providerRepoSQLite,
		MemoryRepo:           memoryRepoSQLite,
		Detector:             ruleDetector,
		Compliance:           ruleComplianceChecker,
		DeidPipeline:         deidentifyPipeline,
		MemoryRetriever:      memoryRetriever,
		ConfidenceAggregator: confidenceAggregator,
		FactRepo:             factRepoSQLite,
		IntentResolver:       intentResolver,
		LocalAnswer:          localAnswerService,
		AccuracyService:      accuracyService,
		KnowledgeSearch:      knowledgeSearchService,
		CitationBuilder:      citationBuilder,
	}
	chatOrchestrator := usecase.NewChatOrchestrator(chatOrchestratorDeps)
	conversationRepoSQLite := repository.NewConversationRepoSQLite(sqlCipherConnector)
	messageRepoSQLite := repository.NewMessageRepoSQLite(sqlCipherConnector)
	disclaimerRepoSQLite := repository.NewDisclaimerRepoSQLite(sqlCipherConnector)
	healthEngine := healthcheck.NewHealthEngine(providerRepoSQLite)
	llmClient := ai.ProviderFactory(appConfig)
	titleGenerator := usecase.NewTitleGenerator(llmClient)
	client := updater.NewDefaultHTTPClient()
	gitHubUpdater := updater.NewGitHubUpdater(client)
	installerAdapter := updater.NewInstallerAdapter()
	service := updater2.NewService(gitHubUpdater, installerAdapter, updateChannel)
	v := _wireValue
	tokenRefreshService := auth.NewTokenRefreshService(providerRepoSQLite, v...)
	oAuthDeviceFlowService := auth.NewOAuthDeviceFlowServiceBare(providerRepoSQLite)
	auditLogRepoSQLite := repository.NewAuditLogRepoSQLite(sqlCipherConnector)
	dialogueRepoSQLite := repository.NewDialogueRepoSQLite(sqlCipherConnector)
	embeddingMigrator := usecase.NewEmbeddingMigrator(factRepoSQLite, embeddingRepoSQLite, embeddingServiceAdapter, migrationState)
	knowledgeChunker := usecase.NewDefaultKnowledgeChunker()
	knowledgeImporter := usecase.NewKnowledgeImporter(knowledgeRepoSQLite, knowledgeChunker, knowledgeTokenizer, embeddingServiceAdapter)
	contextLengthResolver := usecase.NewContextLengthResolver(providerRepoSQLite)
	hfTokenCounter := ai.NewHFTokenCounter()
	contextEstimator := usecase.NewContextEstimator(hfTokenCounter, contextLengthResolver)
	wailsApp := NewWailsApp(chatOrchestrator, memoryRetriever, appConfig, conversationRepoSQLite, messageRepoSQLite, disclaimerRepoSQLite, providerRepoSQLite, healthEngine, titleGenerator, service, keyringStore, tokenRefreshService, oAuthDeviceFlowService, factRepoSQLite, auditLogRepoSQLite, dialogueRepoSQLite, embeddingServiceAdapter, embeddingRepoSQLite, embeddingMigrator, migrationState, accuracyService, knowledgeRepoSQLite, knowledgeImporter, contextLengthResolver, contextEstimator)
	app, cleanup, err := NewApp(wailsApp, sqlCipherConnector, deidentifyPipeline, healthEngine)
	if err != nil {
		return nil, nil, err
	}
	return app, func() {
		cleanup()
	}, nil
}

var (
	_wireValue = []auth.TokenRefreshOption{}
)

// wire.go:

// ProvideDefaultUpdateChannel 根据构建版本返回默认更新通道。
// 正式版默认 stable，预发布或 dev 构建默认 beta。
func ProvideDefaultUpdateChannel() models.UpdateChannel {
	if strings.EqualFold(version, "dev") {
		return models.ChannelBeta
	}
	return models.ParseAppVersion(version).Channel
}
