// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/hzhan516/medmemo/internal/adapters/ai"
	"github.com/hzhan516/medmemo/internal/adapters/auth"
	"github.com/hzhan516/medmemo/internal/adapters/detector"
	"github.com/hzhan516/medmemo/internal/adapters/repository"
	"github.com/hzhan516/medmemo/internal/adapters/updater"
	"github.com/hzhan516/medmemo/internal/application/healthcheck"
	"github.com/hzhan516/medmemo/internal/application/pipeline"
	updater3 "github.com/hzhan516/medmemo/internal/application/updater"
	"github.com/hzhan516/medmemo/internal/application/usecase"
	"github.com/hzhan516/medmemo/internal/infrastructure/config"
	"github.com/hzhan516/medmemo/internal/infrastructure/onnx"
	"github.com/hzhan516/medmemo/internal/infrastructure/secret"
	updater2 "github.com/hzhan516/medmemo/internal/infrastructure/updater"
)

import (
	_ "unsafe"
)

// Injectors from wire.go:

// InitializeApp 通过 Wire 编译期依赖注入组装完整应用。
// 返回 (func()) 作为资源清理回调，由 main 函数通过 defer 调用。
func InitializeApp() (*App, func(), error) {
	llmClientFactory := ai.NewLLMClientFactory()
	loader := NewDefaultLoader()
	appConfig, err := config.LoadConfig(loader)
	if err != nil {
		return nil, nil, err
	}
	keyringStore, err := secret.NewKeyringStore()
	if err != nil {
		return nil, nil, err
	}
	sqlCipherConnector, err := NewSQLCipherConnectorFromConfig(appConfig, keyringStore)
	if err != nil {
		return nil, nil, err
	}
	providerRepoSQLite, err := repository.NewProviderRepoSQLite(sqlCipherConnector, keyringStore)
	if err != nil {
		return nil, nil, err
	}
	memoryRepoSQLite := repository.NewMemoryRepoSQLite(sqlCipherConnector)
	ruleDetector := detector.NewRuleDetector()
	ruleComplianceChecker, err := usecase.NewRuleComplianceChecker()
	if err != nil {
		return nil, nil, err
	}
	l1RuleStage := pipeline.NewL1RuleStage()
	engineConfig := NewEngineConfig(appConfig)
	engine, err := onnx.NewEngine(engineConfig)
	if err != nil {
		return nil, nil, err
	}
	onnxnerDetector := detector.NewONNXNERDetector(engine)
	l2NERStage := pipeline.NewL2NERStage(onnxnerDetector)
	l3KeywordStage := pipeline.NewL3KeywordStage()
	deidentifyPipeline := pipeline.NewDefaultDeidentifyPipeline(l1RuleStage, l2NERStage, l3KeywordStage)
	embeddingServiceAdapter := NewEmbeddingServiceAdapterWithVersion(engine)
	embeddingRepoSQLite := repository.NewEmbeddingRepoSQLite(sqlCipherConnector)
	factRepoSQLite := repository.NewFactRepoSQLite(sqlCipherConnector)
	decayScorer := usecase.NewDecayScorer()
	migrationState := usecase.NewMigrationState()
	queryExpansionService := usecase.NewQueryExpansionService()
	intentResolver := usecase.NewIntentResolver(queryExpansionService)
	memoryRetriever := usecase.NewMemoryRetriever(embeddingServiceAdapter, embeddingRepoSQLite, factRepoSQLite, decayScorer, migrationState, intentResolver, queryExpansionService)
	confidenceAggregator := usecase.NewConfidenceAggregator()
	localAnswerService := usecase.NewLocalAnswerService()
	chatOrchestrator := usecase.NewChatOrchestrator(llmClientFactory, providerRepoSQLite, memoryRepoSQLite, ruleDetector, ruleComplianceChecker, deidentifyPipeline, memoryRetriever, confidenceAggregator, factRepoSQLite, intentResolver, localAnswerService)
	conversationRepoSQLite := repository.NewConversationRepoSQLite(sqlCipherConnector)
	messageRepoSQLite := repository.NewMessageRepoSQLite(sqlCipherConnector)
	disclaimerRepoSQLite := repository.NewDisclaimerRepoSQLite(sqlCipherConnector)
	healthEngine := healthcheck.NewHealthEngine(providerRepoSQLite)
	llmClient := ai.ProviderFactory(appConfig)
	titleGenerator := usecase.NewTitleGenerator(llmClient)
	client := updater.NewDefaultHTTPClient()
	gitHubUpdater := updater.NewGitHubUpdater(client)
	installer := updater2.NewInstaller()
	service := updater3.NewService(gitHubUpdater, installer)
	tokenRefreshService := auth.NewTokenRefreshServiceBare(providerRepoSQLite)
	oAuthDeviceFlowService := auth.NewOAuthDeviceFlowServiceBare(providerRepoSQLite)
	auditLogRepoSQLite := repository.NewAuditLogRepoSQLite(sqlCipherConnector)
	dialogueRepoSQLite := repository.NewDialogueRepoSQLite(sqlCipherConnector)
	embeddingMigrator := usecase.NewEmbeddingMigrator(factRepoSQLite, embeddingRepoSQLite, embeddingServiceAdapter, migrationState)
	wailsApp := NewWailsApp(chatOrchestrator, memoryRetriever, appConfig, conversationRepoSQLite, messageRepoSQLite, disclaimerRepoSQLite, providerRepoSQLite, healthEngine, titleGenerator, service, keyringStore, tokenRefreshService, oAuthDeviceFlowService, factRepoSQLite, auditLogRepoSQLite, dialogueRepoSQLite, embeddingServiceAdapter, embeddingRepoSQLite, embeddingMigrator, migrationState)
	app, cleanup, err := NewApp(wailsApp, sqlCipherConnector, deidentifyPipeline, healthEngine)
	if err != nil {
		return nil, nil, err
	}
	return app, func() {
		cleanup()
	}, nil
}
