/**
 * 医学术语词典（简化版，框架实现）。
 * 后续 Sprint 中逐步扩充至完整词库。
 */

export interface MedicalTermEntry {
  term: string
  definition: string
}

const TERMS: MedicalTermEntry[] = [
  { term: '高血压', definition: '动脉血压持续升高的慢性疾病，可能增加心脑血管疾病风险。' },
  { term: '糖尿病', definition: '一种代谢性疾病，特征为血糖水平长期高于正常值。' },
  { term: '低血糖', definition: '血糖浓度低于正常水平，可能出现头晕、出汗、心悸等症状。' },
  { term: '心绞痛', definition: '心肌暂时性缺血引起的胸痛或不适感。' },
  { term: '心肌梗死', definition: '冠状动脉急性闭塞导致心肌缺血坏死，俗称"心脏病发作"。' },
  { term: '脑卒中', definition: '脑部血液供应障碍导致脑组织损伤，包括缺血性和出血性两种。' },
  { term: '脑梗死', definition: '脑部血液供应障碍导致脑组织缺血缺氧性坏死。' },
  { term: '脑出血', definition: '脑内血管破裂导致血液流入脑组织。' },
  { term: '心律失常', definition: '心脏搏动的频率、节律、起源部位或传导速度异常。' },
  { term: '心房颤动', definition: '最常见的心律失常类型，心房电活动紊乱导致心跳不规则。' },
  { term: '心力衰竭', definition: '心脏泵血功能受损，无法满足身体代谢需要。' },
  { term: '冠心病', definition: '冠状动脉粥样硬化导致心肌缺血、缺氧或坏死的心脏病。' },
  { term: '动脉硬化', definition: '动脉壁增厚、变硬、失去弹性的病理变化。' },
  { term: '动脉粥样硬化', definition: '动脉内膜脂质沉积形成斑块，导致血管狭窄。' },
  { term: '高血脂', definition: '血液中脂质（胆固醇、甘油三酯）水平异常升高。' },
  { term: '高胆固醇', definition: '血液中胆固醇含量超过正常范围。' },
  { term: '甘油三酯', definition: '血液中的一种脂质，过高可能增加心血管疾病风险。' },
  { term: '低密度脂蛋白', definition: '俗称"坏胆固醇"，过高会促进动脉粥样硬化。' },
  { term: '高密度脂蛋白', definition: '俗称"好胆固醇"，有助于清除血管中的胆固醇。' },
  { term: '胰岛素', definition: '胰腺分泌的激素，调节血糖水平。' },
  { term: '胰岛素抵抗', definition: '靶组织对胰岛素敏感性下降，导致血糖调节异常。' },
  { term: '甲状腺功能亢进', definition: '甲状腺激素分泌过多，导致代谢率增高。' },
  { term: '甲状腺功能减退', definition: '甲状腺激素分泌不足，导致代谢率降低。' },
  { term: '甲状腺结节', definition: '甲状腺内的肿块，多数为良性。' },
  { term: '贫血', definition: '血液中红细胞数量或血红蛋白浓度低于正常水平。' },
  { term: '白细胞', definition: '血液中的免疫细胞，负责抵御感染。' },
  { term: '红细胞', definition: '血液中的携氧细胞，含有血红蛋白。' },
  { term: '血小板', definition: '血液中的细胞碎片，参与凝血过程。' },
  { term: '血红蛋白', definition: '红细胞中的蛋白质，负责运输氧气。' },
  { term: '炎症', definition: '机体对损伤因子产生的防御性反应，表现为红、肿、热、痛。' },
  { term: '感染', definition: '病原体侵入机体并在体内生长繁殖引起的病理过程。' },
  { term: '抗生素', definition: '用于治疗细菌感染的药物，对病毒无效。' },
  { term: '抗病毒药物', definition: '用于治疗病毒感染的药物。' },
  { term: '疫苗', definition: '用于预防传染病的生物制品，可刺激机体产生免疫力。' },
  { term: '免疫力', definition: '机体识别和清除外来病原体及异常细胞的能力。' },
  { term: '自身免疫', definition: '免疫系统错误地攻击自身正常组织。' },
  { term: '过敏反应', definition: '免疫系统对通常无害物质的过度反应。' },
  { term: '哮喘', definition: '慢性气道炎症性疾病，特征为反复发作的喘息、气促。' },
  { term: '慢性阻塞性肺病', definition: '以持续气流受限为特征的肺部疾病，包括慢性支气管炎和肺气肿。' },
  { term: '肺气肿', definition: '肺泡壁破坏导致肺泡异常扩大的病理状态。' },
  { term: '肺炎', definition: '肺实质的炎症，通常由细菌、病毒或真菌感染引起。' },
  { term: '肺结核', definition: '由结核分枝杆菌引起的慢性传染病，主要侵犯肺部。' },
  { term: '肺癌', definition: '发生于肺部的恶性肿瘤。' },
  { term: '胃癌', definition: '发生于胃部的恶性肿瘤。' },
  { term: '肝癌', definition: '发生于肝脏的恶性肿瘤。' },
  { term: '结肠癌', definition: '发生于结肠的恶性肿瘤。' },
  { term: '乳腺癌', definition: '发生于乳腺的恶性肿瘤，女性最常见。' },
  { term: '宫颈癌', definition: '发生于宫颈的恶性肿瘤，与HPV感染密切相关。' },
  { term: '前列腺', definition: '男性生殖系统腺体，位于膀胱下方。' },
  { term: '前列腺增生', definition: '前列腺组织良性增生，常见于老年男性。' },
  { term: '骨折', definition: '骨头的连续性或完整性中断。' },
  { term: '骨质疏松', definition: '骨量减少、骨微结构破坏导致骨脆性增加的代谢性骨病。' },
  { term: '关节炎', definition: '关节的炎症性疾病，常见类型包括骨关节炎和类风湿关节炎。' },
  { term: '类风湿关节炎', definition: '慢性自身免疫性疾病，主要侵犯关节滑膜。' },
  { term: '痛风', definition: '尿酸盐结晶沉积引起的关节炎，常表现为急性关节剧痛。' },
  { term: '椎间盘突出', definition: '椎间盘纤维环破裂，髓核突出压迫神经。' },
  { term: '腰椎间盘突出', definition: '腰椎间盘向后突出压迫神经根或脊髓。' },
  { term: '颈椎病', definition: '颈椎退行性病变引起的综合征。' },
  { term: '偏头痛', definition: '反复发作的一侧或双侧搏动性头痛。' },
  { term: '癫痫', definition: '大脑神经元异常放电导致的短暂性脑功能障碍。' },
  { term: '帕金森病', definition: '中枢神经系统退行性疾病，主要影响运动功能。' },
  { term: '阿尔茨海默病', definition: '最常见的痴呆类型，以进行性认知功能下降为特征。' },
  { term: '痴呆', definition: '以获得性认知功能障碍为核心特征的综合征。' },
  { term: '抑郁', definition: '以显著而持久的心境低落为主要特征的精神障碍。' },
  { term: '焦虑', definition: '以过度担忧、紧张不安为主要特征的精神状态。' },
  { term: '失眠', definition: '睡眠启动或维持困难，导致睡眠质量或数量不足。' },
  { term: '睡眠呼吸暂停', definition: '睡眠中反复出现呼吸暂停或低通气。' },
  { term: '胃食管反流', definition: '胃内容物反流入食管引起的不适或并发症。' },
  { term: '胃溃疡', definition: '胃黏膜被胃酸和胃蛋白酶消化形成的溃疡。' },
  { term: '十二指肠溃疡', definition: '十二指肠黏膜被消化液消化形成的溃疡。' },
  { term: '胃炎', definition: '胃黏膜的炎症。' },
  { term: '肠易激综合征', definition: '以腹痛、腹胀伴排便习惯改变为特征的功能性肠病。' },
  { term: '便秘', definition: '排便频率减少、粪便干硬或排便困难。' },
  { term: '腹泻', definition: '排便次数增多、粪便稀薄。' },
  { term: '肝硬化', definition: '各种慢性肝病发展的晚期阶段，以肝组织弥漫性纤维化、假小叶形成为特征。' },
  { term: '脂肪肝', definition: '肝细胞内脂肪堆积过多的病变。' },
  { term: '肝炎', definition: '肝脏的炎症，常见病因包括病毒、酒精、药物等。' },
  { term: '乙型肝炎', definition: '由乙型肝炎病毒引起的肝脏炎症。' },
  { term: '丙型肝炎', definition: '由丙型肝炎病毒引起的肝脏炎症。' },
  { term: '胆囊炎', definition: '胆囊的炎症，常由胆囊结石引起。' },
  { term: '胆囊结石', definition: '胆囊内形成的固体结晶物质。' },
  { term: '肾结石', definition: '肾脏内形成的固体矿物质结晶。' },
  { term: '尿路感染', definition: '病原体侵入尿路引起的炎症。' },
  { term: '慢性肾病', definition: '肾脏结构或功能异常持续超过3个月。' },
  { term: '尿毒症', definition: '肾功能严重损害导致代谢废物和毒素蓄积的临床综合征。' },
  { term: '透析', definition: '替代肾脏清除体内代谢废物和多余水分的治疗方法。' },
  { term: '白内障', definition: '晶状体混浊导致视力下降的眼病。' },
  { term: '青光眼', definition: '眼压升高导致视神经损害的眼病。' },
  { term: '黄斑变性', definition: '黄斑区结构衰老性改变，导致中心视力下降。' },
  { term: '视网膜', definition: '眼球后部的感光神经层。' },
  { term: '角膜', definition: '眼球前部的透明组织。' },
  { term: '屈光不正', definition: '眼睛在调节放松状态下，平行光线不能准确聚焦于视网膜上。' },
  { term: '近视', definition: '屈光不正的一种，远处物体成像于视网膜前。' },
  { term: '远视', definition: '屈光不正的一种，近处物体成像于视网膜后。' },
  { term: '散光', definition: '角膜或晶状体表面曲率不规则导致的屈光不正。' },
  { term: '干眼症', definition: '泪液质或量异常导致泪膜稳定性下降的眼表疾病。' },
  { term: '结膜炎', definition: '结膜的炎症，常见症状为眼红、分泌物增多。' },
  { term: '中耳炎', definition: '中耳的炎症，可分为急性和慢性。' },
  { term: '鼻炎', definition: '鼻腔黏膜的炎症。' },
  { term: '鼻窦炎', definition: '鼻窦黏膜的炎症。' },
  { term: '扁桃体炎', definition: '扁桃体的炎症。' },
  { term: '咽炎', definition: '咽部黏膜的炎症。' },
  { term: '喉炎', definition: '喉部黏膜的炎症。' },
  { term: '支气管炎', definition: '支气管黏膜的炎症。' },
  { term: '心电图', definition: '记录心脏电活动的检查方法。' },
  { term: 'CT', definition: '计算机断层扫描，利用X射线进行断层成像。' },
  { term: 'MRI', definition: '磁共振成像，利用磁场和射频脉冲进行成像。' },
  { term: 'X光', definition: '利用X射线穿透人体形成影像的检查方法。' },
  { term: '超声', definition: '利用超声波进行医学成像的检查方法。' },
  { term: '胃镜', definition: '经口插入内镜检查食管、胃和十二指肠。' },
  { term: '肠镜', definition: '经肛门插入内镜检查结肠和直肠。' },
  { term: '活检', definition: '从活体组织取少量样本进行病理检查。' },
  { term: '病理', definition: '研究疾病发生发展规律的医学学科。' },
  { term: '血常规', definition: '检测血液中各类细胞数量和形态的常规检查。' },
  { term: '尿常规', definition: '检测尿液理化性质和成分的常规检查。' },
  { term: '肝功能', definition: '检测肝脏代谢功能和肝细胞损伤的指标。' },
  { term: '肾功能', definition: '检测肾脏排泄和代谢功能的指标。' },
  { term: '血脂', definition: '检测血液中脂质含量的检查。' },
  { term: '血糖', definition: '检测血液中葡萄糖浓度的检查。' },
  { term: '糖化血红蛋白', definition: '反映近2-3个月平均血糖水平的指标。' },
  { term: '肿瘤标志物', definition: '由肿瘤细胞产生或机体对肿瘤反应而产生的物质。' },
  { term: '基因', definition: '遗传的基本单位，携带遗传信息的DNA片段。' },
  { term: '遗传', definition: '亲代将性状传递给子代的过程。' },
  { term: '家族病史', definition: '家族成员中某种疾病的发病情况。' },
  { term: '并发症', definition: '在原发疾病基础上并发的其他疾病。' },
  { term: '预后', definition: '对疾病发展趋势和结局的预测。' },
  { term: '发病率', definition: '一定时期内某人群中新发病例的比例。' },
  { term: '患病率', definition: '某一时点某人群中现患病例的比例。' },
  { term: '死亡率', definition: '一定时期内死亡人数占总人口的比例。' },
  { term: '猝死', definition: '貌似健康者因自然疾病突然发生的意外死亡。' },
  { term: '急救', definition: '对急危重症患者进行的紧急救治。' },
  { term: '心肺复苏', definition: '针对心跳呼吸骤停患者采取的紧急救治措施。' },
  { term: '止血', definition: '控制出血的急救措施。' },
  { term: '包扎', definition: '用敷料覆盖并固定伤口的处理方法。' },
  { term: '消毒', definition: '杀灭或清除病原微生物的方法。' },
  { term: '无菌', definition: '不存在活的微生物的状态。' },
  { term: '抗生素耐药性', definition: '细菌对抗生素产生抵抗能力的现象。' },
  { term: '副作用', definition: '药物在治疗剂量下出现的与治疗目的无关的作用。' },
  { term: '禁忌症', definition: '禁止使用某种药物或治疗方法的情况。' },
  { term: '剂量', definition: '药物的使用量。' },
  { term: '疗程', definition: '连续用药的时间。' },
  { term: '处方药', definition: '必须凭执业医师处方才能调配、购买和使用的药品。' },
  { term: '非处方药', definition: '不需要处方即可自行判断、购买和使用的药品。' },
  { term: '中成药', definition: '以中药材为原料，按规定的处方和工艺生产的药品。' },
  { term: '西药', definition: '用化学合成方法制成或从天然产物提制的药物。' },
  { term: '保健品', definition: '具有特定保健功能的食品，不能替代药物治疗。' },
  { term: '维生素', definition: '维持人体正常生理功能所必需的微量有机物质。' },
  { term: '矿物质', definition: '人体必需的无机元素。' },
  { term: '蛋白质', definition: '由氨基酸组成的大分子，是生命活动的主要承担者。' },
  { term: '脂肪', definition: '人体重要的能量来源和结构成分。' },
  { term: '碳水化合物', definition: '人体主要的能量来源。' },
  { term: '膳食纤维', definition: '不能被人体消化吸收的多糖类物质。' },
  { term: '卡路里', definition: '能量单位，常用于表示食物所含能量。' },
  { term: 'BMI', definition: '身体质量指数，体重(kg)除以身高(m)的平方。' },
  { term: '体温', definition: '人体内部的温度，正常范围约36.0-37.2°C。' },
  { term: '脉搏', definition: '动脉搏动的频率，正常成人安静时60-100次/分。' },
  { term: '呼吸', definition: '机体与外界环境之间进行气体交换的过程。' },
  { term: '血压', definition: '血液在血管内流动时对血管壁的侧压力。' },
  { term: '收缩压', definition: '心脏收缩时动脉血压的最高值。' },
  { term: '舒张压', definition: '心脏舒张时动脉血压的最低值。' },
  { term: '症状', definition: '患者主观感受到的异常或不适。' },
  { term: '体征', definition: '医生通过检查发现的客观异常表现。' },
  { term: '诊断', definition: '通过病史、体检和辅助检查判断疾病的过程。' },
  { term: '鉴别诊断', definition: '通过比较分析排除相似疾病、确定正确诊断的过程。' },
  { term: '治疗方案', definition: '针对疾病制定的系统性治疗计划。' },
  { term: '随访', definition: '治疗后定期复查以评估疗效和监测复发。' },
  { term: '转诊', definition: '将患者从基层医疗机构转往上级医疗机构就诊。' },
  { term: '挂号', definition: '患者在医院就诊前进行的登记预约。' },
  { term: '门诊', definition: '患者在医院非住院的诊疗方式。' },
  { term: '住院', definition: '患者入住医院接受系统治疗和观察。' },
  { term: '急诊', definition: '为急危重症患者提供的紧急医疗服务。' },
  { term: 'ICU', definition: '重症监护病房，收治危重病患者。' },
  { term: '手术室', definition: '进行手术操作的专门场所。' },
  { term: '麻醉', definition: '用药物或其他方法使患者暂时失去知觉或痛觉。' },
  { term: '全身麻醉', definition: '使患者意识消失、全身无痛的麻醉方式。' },
  { term: '局部麻醉', definition: '使身体某一部分感觉消失的麻醉方式。' },
  { term: '微创手术', definition: '通过微小切口进行的手术，创伤小、恢复快。' },
  { term: '开放手术', definition: '通过较大切口直接暴露手术区域的手术方式。' },
  { term: '放疗', definition: '利用放射线治疗肿瘤的方法。' },
  { term: '化疗', definition: '利用化学药物治疗肿瘤的方法。' },
  { term: '免疫治疗', definition: '通过调节机体免疫系统治疗疾病的方法。' },
  { term: '靶向治疗', definition: '针对肿瘤细胞特定分子靶点的治疗方法。' },
  { term: '基因治疗', definition: '通过修正或替换异常基因治疗疾病的方法。' },
  { term: '干细胞', definition: '具有自我更新和分化潜能的细胞。' },
  { term: '器官移植', definition: '将健康的器官移植到患者体内替代病变器官。' },
  { term: '配型', definition: '供受体之间组织相容性抗原的匹配检测。' },
  { term: '排斥反应', definition: '受者免疫系统攻击移植器官的反应。' },
  { term: '免疫抑制剂', definition: '抑制机体免疫反应的药物。' },
  { term: '激素', definition: '由内分泌腺分泌的高效生物活性物质。' },
  { term: '内分泌', definition: '腺体分泌激素直接进入血液循环的系统。' },
  { term: '新陈代谢', definition: '机体与外界环境进行物质和能量交换的过程。' },
  { term: '酸碱平衡', definition: '机体维持体液pH值相对稳定的状态。' },
  { term: '电解质', definition: '体液中溶解的离子，如钠、钾、钙等。' },
  { term: '脱水', definition: '体内水分丢失过多导致体液容量不足。' },
  { term: '水肿', definition: '组织间隙液体过多积聚。' },
  { term: '休克', definition: '有效循环血量锐减导致组织灌注不足的危急状态。' },
  { term: '昏迷', definition: '意识完全丧失的状态。' },
  { term: '意识障碍', definition: '人对周围环境及自身状态的识别和觉察能力异常。' },
  { term: '抽搐', definition: '骨骼肌不自主的强直或阵挛性收缩。' },
  { term: '瘫痪', definition: '肢体或躯体某部分运动功能丧失。' },
  { term: '麻木', definition: '皮肤感觉减退或消失。' },
  { term: '眩晕', definition: '自身或周围物体旋转的运动幻觉。' },
  { term: '晕厥', definition: '一过性大脑供血不足导致的短暂意识丧失。' },
  { term: '呼吸困难', definition: '患者主观感到空气不足、呼吸费力。' },
  { term: '咳嗽', definition: '呼吸道受到刺激引起的保护性反射动作。' },
  { term: '咳痰', definition: '咳嗽时排出呼吸道分泌物。' },
  { term: '咯血', definition: '喉及喉以下呼吸道出血经口腔咳出。' },
  { term: '呕血', definition: '上消化道出血经口腔呕出。' },
  { term: '便血', definition: '消化道出血经肛门排出。' },
  { term: '黑便', definition: '上消化道出血后血液经肠道分解形成的黑色柏油样便。' },
  { term: '黄疸', definition: '血清胆红素升高导致皮肤、黏膜和巩膜黄染。' },
  { term: '皮疹', definition: '皮肤外观的异常改变。' },
  { term: '瘙痒', definition: '皮肤或黏膜引起抓挠欲望的感觉。' },
  { term: '溃疡', definition: '皮肤或黏膜表面组织的局限性缺损。' },
  { term: '糜烂', definition: '皮肤或黏膜上皮浅表性缺损，未达真皮层。' },
  { term: '结节', definition: '真皮或皮下组织的局限性实质性损害。' },
  { term: '囊肿', definition: '内含液体或半固体物质的囊性包块。' },
  { term: '肿瘤', definition: '机体细胞异常增殖形成的新生物。' },
  { term: '良性肿瘤', definition: '生长缓慢、不发生转移、预后较好的肿瘤。' },
  { term: '恶性肿瘤', definition: '生长迅速、可发生转移、预后较差的肿瘤。' },
  { term: '转移', definition: '肿瘤细胞从原发部位扩散到身体其他部位。' },
  { term: '复发', definition: '疾病治愈或缓解后再次出现。' },
  { term: '后遗症', definition: '疾病治愈后遗留的功能障碍或结构异常。' },
  { term: '残疾', definition: '因疾病或损伤导致的身体功能或结构永久性丧失。' },
  { term: '康复', definition: '通过综合措施使患者在身体、心理和社会功能上得到恢复。' },
  { term: '理疗', definition: '利用物理因子治疗疾病的方法。' },
  { term: '针灸', definition: '中医传统疗法，通过刺激穴位调节经络气血。' },
  { term: '推拿', definition: '中医传统疗法，通过手法作用于体表特定部位。' },
  { term: '拔罐', definition: '中医传统疗法，利用负压吸附于体表。' },
  { term: '艾灸', definition: '中医传统疗法，利用艾绒燃烧产生的热力刺激穴位。' },
  { term: '中药', definition: '中医理论指导下使用的天然药物及其加工品。' },
  { term: '方剂', definition: '根据中医理论和治法组成的药物配伍。' },
  { term: '辨证论治', definition: '中医诊断和治疗疾病的基本原则。' },
  { term: '气血', definition: '中医学中人体生命活动的两种基本物质。' },
  { term: '阴阳', definition: '中医学解释人体生理病理的基本概念。' },
  { term: '五行', definition: '中医学解释事物相互关系的五种基本属性。' },
  { term: '经络', definition: '中医学中运行气血、联络脏腑肢节的通道系统。' },
  { term: '穴位', definition: '经络之气输注于体表的部位。' },
  { term: '脉象', definition: '中医通过切脉感知到的脉搏形象。' },
  { term: '舌诊', definition: '中医通过观察舌象诊断疾病的方法。' },
  { term: '望闻问切', definition: '中医四种基本诊法。' },
  { term: '治未病', definition: '中医预防医学思想，强调未病先防、既病防变。' },
  { term: '养生', definition: '通过各种方法调养身体、增强体质、预防疾病。' },
  { term: '食疗', definition: '利用食物的性味功效调养身体、防治疾病。' },
  { term: '体质', definition: '人体在先天遗传和后天获得基础上形成的相对稳定的特质。' },
  { term: '亚健康', definition: '介于健康和疾病之间的状态。' },
  { term: '慢性病', definition: '病程长、进展缓慢的非传染性疾病。' },
  { term: '急性病', definition: '发病急、病程短的疾病。' },
  { term: '传染病', definition: '由病原体引起、可在人与人或动物与人之间传播的疾病。' },
  { term: '职业病', definition: '因职业活动引起的疾病。' },
  { term: '地方病', definition: '局限于某些特定地区发生的疾病。' },
  { term: '遗传病', definition: '由遗传物质改变引起的疾病。' },
  { term: '先天性疾病', definition: '出生前已存在的结构或功能异常。' },
  { term: '后天性疾病', definition: '出生后因各种因素获得的疾病。' },
  { term: '器质性疾病', definition: '器官组织结构发生病理改变的疾病。' },
  { term: '功能性疾病', definition: '器官组织结构无明显改变，但功能异常的疾病。' },
  { term: '原发疾病', definition: '最初发生、非由其他疾病引起的疾病。' },
  { term: '继发疾病', definition: '由其他疾病引起的疾病。' },
  { term: '综合征', definition: '一组同时出现的症状和体征。' },
  { term: '后遗症', definition: '疾病治愈后遗留的功能障碍。' },
  { term: '高危人群', definition: '某种疾病发病风险较高的人群。' },
  { term: '易感人群', definition: '对某种传染病缺乏免疫力而容易感染的人群。' },
  { term: '流行病学', definition: '研究疾病在人群中的分布、发生发展规律及防治策略的学科。' },
  { term: '循证医学', definition: '基于最佳研究证据进行临床决策的医学模式。' },
  { term: '精准医学', definition: '根据个体基因、环境和生活方式差异制定个性化治疗方案。' },
  { term: '远程医疗', definition: '利用通信技术远距离提供医疗服务。' },
  { term: '互联网医院', definition: '依托实体医疗机构提供在线诊疗服务的平台。' },
  { term: '健康管理', definition: '对个体或群体健康进行全面监测、分析和评估。' },
  { term: '健康体检', definition: '通过医学手段对健康状态进行的检查。' },
  { term: '筛查', definition: '运用快速简便的方法从表面健康人群中识别出可能患病者。' },
  { term: '早诊早治', definition: '在疾病早期发现并及时治疗，以提高治愈率。' },
  { term: '一级预防', definition: '针对致病因素采取的措施，防止疾病发生。' },
  { term: '二级预防', definition: '早期发现、早期诊断、早期治疗。' },
  { term: '三级预防', definition: '防止疾病恶化、减少并发症和后遗症。' },
  { term: '院前急救', definition: '患者到达医院前实施的紧急医疗救护。' },
  { term: '绿色通道', definition: '医院为急危重症患者提供的快速救治流程。' },
  { term: '多学科会诊', definition: '多个学科专家共同讨论疑难病例的诊疗方案。' },
  { term: '临床路径', definition: '针对特定疾病制定的标准化诊疗流程。' },
  { term: '病历', definition: '记录患者疾病的发生、发展、诊疗经过的医疗文书。' },
  { term: '电子病历', definition: '以电子形式存储和管理的病历。' },
  { term: '知情同意', definition: '患者充分了解诊疗信息后自愿作出的同意决定。' },
  { term: '隐私保护', definition: '对患者的个人信息和医疗信息进行保密。' },
  { term: '医疗纠纷', definition: '医患双方对医疗行为及其后果产生的争议。' },
  { term: '医疗事故', definition: '医疗机构及其医务人员在医疗活动中过失造成患者人身损害。' },
  { term: '医疗质量', definition: '医疗服务满足患者需求和期望的程度。' },
  { term: '患者安全', definition: '在医疗过程中避免患者受到伤害。' },
  { term: '用药安全', definition: '在药物使用过程中避免或减少用药错误和不良反应。' },
  { term: '合理用药', definition: '根据疾病种类、患者状况和药理学理论选择最佳药物和剂量。' },
  { term: '药物相互作用', definition: '两种或多种药物同时使用时产生的相互影响。' },
  { term: '不良反应', definition: '合格药品在正常用法用量下出现的与用药目的无关的有害反应。' },
  { term: '过敏反应', definition: '免疫系统对药物的异常反应。' },
  { term: '药物依赖', definition: '长期用药后机体对药物产生生理或心理依赖。' },
  { term: '成瘾', definition: '对某种物质产生强烈的渴求和依赖。' },
  { term: '戒断症状', definition: '停止用药后出现的一系列生理和心理症状。' },
  { term: '耐受性', definition: '长期用药后机体对药物反应性降低。' },
  { term: '个体化用药', definition: '根据患者的基因型、生理状态等制定个体化给药方案。' },
  { term: '血药浓度', definition: '药物在血液中的浓度。' },
  { term: '半衰期', definition: '药物在体内浓度下降一半所需的时间。' },
  { term: '生物利用度', definition: '药物吸收进入体循环的相对量和速度。' },
  { term: '首过效应', definition: '药物经胃肠道吸收后首次通过肝脏时被代谢。' },
  { term: '代谢', definition: '药物在体内发生的化学结构变化。' },
  { term: '排泄', definition: '药物及其代谢产物排出体外的过程。' },
  { term: '分布', definition: '药物从血液向组织器官转运的过程。' },
  { term: '吸收', definition: '药物从用药部位进入血液循环的过程。' },
  { term: '给药途径', definition: '药物进入机体的方式，如口服、注射、外用等。' },
  { term: '静脉注射', definition: '将药物直接注入静脉血管。' },
  { term: '肌肉注射', definition: '将药物注入肌肉组织。' },
  { term: '皮下注射', definition: '将药物注入皮下组织。' },
  { term: '口服', definition: '经口摄入药物。' },
  { term: '舌下含服', definition: '将药物置于舌下含化吸收。' },
  { term: '吸入', definition: '经呼吸道吸入药物。' },
  { term: '外用', definition: '将药物涂抹于皮肤表面。' },
  { term: '栓剂', definition: '通过肛门或阴道给药的固体剂型。' },
  { term: '贴剂', definition: '贴于皮肤表面经皮吸收给药的剂型。' },
  { term: '滴眼液', definition: '用于眼部的液体制剂。' },
  { term: '滴耳液', definition: '用于耳部的液体制剂。' },
  { term: '滴鼻液', definition: '用于鼻部的液体制剂。' },
  { term: '喷雾剂', definition: '借助抛射剂或机械泵将药物呈雾状喷出的制剂。' },
  { term: '缓释制剂', definition: '能缓慢释放药物的制剂，延长药效。' },
  { term: '控释制剂', definition: '按预定速度释放药物的制剂。' },
  { term: '肠溶制剂', definition: '在肠道溶解吸收的制剂，避免胃酸破坏。' },
  { term: '胶囊', definition: '将药物填充于空心胶囊中的固体剂型。' },
  { term: '片剂', definition: '药物与辅料压制而成的扁平或凸面固体剂型。' },
  { term: '颗粒剂', definition: '药物与辅料制成的干燥颗粒状制剂。' },
  { term: '散剂', definition: '一种或多种药物均匀混合制成的粉末状制剂。' },
  { term: '溶液剂', definition: '药物溶解于溶剂中形成的澄清液体制剂。' },
  { term: '混悬剂', definition: '固体药物微粒分散在液体中形成的非均相液体制剂。' },
  { term: '乳剂', definition: '两种互不相溶的液体经乳化形成的非均相液体制剂。' },
  { term: '软膏', definition: '药物与适宜基质制成的具有适当稠度的膏状外用制剂。' },
  { term: '乳膏', definition: '药物溶解或分散于乳状液基质中的半固体制剂。' },
  { term: '凝胶', definition: '药物与凝胶基质制成的半固体制剂。' },
  { term: '洗剂', definition: '供涂敷皮肤用的液体制剂。' },
  { term: '酊剂', definition: '药物用规定浓度的乙醇提取或溶解制成的液体制剂。' },
  { term: '煎膏剂', definition: '中药材用水煎煮、浓缩后加炼蜜或糖制成的半流体制剂。' },
  { term: '丸剂', definition: '药物与辅料制成的球形或类球形固体制剂。' },
  { term: '丹剂', definition: '汞及某些矿物药在高温下炼制而成的无机化合物制剂。' },
  { term: '茶剂', definition: '含茶叶或不含茶叶的药材粗粉或碎片，用沸水冲泡服用的制剂。' },
  { term: '酒剂', definition: '药材用蒸馏酒浸提制成的澄清液体制剂。' },
  { term: '露剂', definition: '芳香性药材经水蒸气蒸馏法制得的饱和或近饱和水溶液。' },
  { term: '锭剂', definition: '药物细粉加适宜黏合剂制成的固体制剂。' },
  { term: '膜剂', definition: '药物与成膜材料制成的薄膜状制剂。' },
  { term: '气雾剂', definition: '药物与抛射剂封装于耐压容器中制成的制剂。' },
  { term: '粉雾剂', definition: '微粉化药物与载体装入干粉吸入装置中的制剂。' },
  { term: '注射剂', definition: '药物制成的供注入体内的无菌溶液、乳状液或混悬液。' },
  { term: '输液', definition: '大剂量注射液，通过静脉滴注输入体内。' },
  { term: '粉针剂', definition: '无菌粉末，临用前用适宜溶剂溶解后注射。' },
  { term: '冻干粉针', definition: '经冷冻干燥制成的无菌粉末注射剂。' },
  { term: '水针剂', definition: '药物制成的无菌水溶液注射剂。' },
  { term: '大输液', definition: '容量大于等于50ml的静脉输液制剂。' },
  { term: '小容量注射剂', definition: '容量小于50ml的注射剂。' },
  { term: '脂质体', definition: '将药物包封于类脂质双分子层内形成的微型囊泡。' },
  { term: '纳米粒', definition: '粒径在10-1000nm的固态胶体颗粒。' },
  { term: '微球', definition: '药物分散或包埋于高分子材料中形成的球形或类球形微粒。' },
  { term: '植入剂', definition: '埋植于皮下缓慢释放药物的固体制剂。' },
]

/** 术语集合，用于快速查找 */
const TERM_SET = new Set(TERMS.map((t) => t.term))

/** 术语定义映射 */
const DEFINITION_MAP = new Map(TERMS.map((t) => [t.term, t.definition]))

/** 全局正则实例（按术语长度降序，避免短词匹配干扰长词） */
let _regex: RegExp | null = null

export function getMedicalTermsRegex(): RegExp {
  if (!_regex) {
    const sorted = TERMS.map((t) => t.term).sort((a, b) => b.length - a.length)
    const escaped = sorted.map((t) => t.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'))
    _regex = new RegExp(`(${escaped.join('|')})`, 'g')
  }
  return _regex
}

export function isMedicalTerm(text: string): boolean {
  return TERM_SET.has(text)
}

export function getMedicalDefinition(term: string): string | undefined {
  return DEFINITION_MAP.get(term)
}

export function getAllMedicalTerms(): MedicalTermEntry[] {
  return TERMS
}
