// Caution: this file type should not be changed manually. It is generated by Wails CLI.

export interface SendMessageRequest {
  conversation_id: string;
  messages: Array<{ role: string; content: string }>;
  model: string;
}

export interface SendMessageResponse {
  reply: string;
  confidence: number;
  warnings: Array<string>;
}

export interface ConversationSummary {
  id: string;
  title: string;
  updated_at: string;
}

export interface ModelInfo {
  id: string;
  name: string;
  provider: string;
}

export interface EmergencyResult {
  level: string;
  message: string;
  action: string;
}

export function SendMessage(arg1: SendMessageRequest): Promise<SendMessageResponse>;

export function SendMessageStream(arg1: SendMessageRequest): Promise<void>;

export function StopGeneration(): Promise<void>;

export function GetConversations(): Promise<Array<ConversationSummary>>;

export function CreateConversation(): Promise<string>;

export function GetModels(): Promise<Array<ModelInfo>>;

export function CheckEmergency(arg1: string): Promise<EmergencyResult>;

export function GenerateTitle(arg1: string, arg2: string): Promise<void>;

export function ShowEmergencyDialog(arg1: string, arg2: string): Promise<void>;
