// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptDisclaimer(arg1) {
  return window['go']['main']['WailsApp']['AcceptDisclaimer'](arg1);
}

export function ApplyUpdate(arg1) {
  return window['go']['main']['WailsApp']['ApplyUpdate'](arg1);
}

export function BuildCLIProvider(arg1, arg2) {
  return window['go']['main']['WailsApp']['BuildCLIProvider'](arg1, arg2);
}

export function CancelOAuthDeviceFlow(arg1) {
  return window['go']['main']['WailsApp']['CancelOAuthDeviceFlow'](arg1);
}

export function CollectSystemInfo() {
  return window['go']['main']['WailsApp']['CollectSystemInfo']();
}

export function CheckEmergency(arg1) {
  return window['go']['main']['WailsApp']['CheckEmergency'](arg1);
}

export function CheckProviderHealth(arg1) {
  return window['go']['main']['WailsApp']['CheckProviderHealth'](arg1);
}

export function CheckUpdate() {
  return window['go']['main']['WailsApp']['CheckUpdate']();
}

export function CreateConversation() {
  return window['go']['main']['WailsApp']['CreateConversation']();
}

export function CreateOllamaProvider() {
  return window['go']['main']['WailsApp']['CreateOllamaProvider']();
}

export function CreateProvider(arg1) {
  return window['go']['main']['WailsApp']['CreateProvider'](arg1);
}

export function DeclineDisclaimer() {
  return window['go']['main']['WailsApp']['DeclineDisclaimer']();
}

export function DeleteConversation(arg1) {
  return window['go']['main']['WailsApp']['DeleteConversation'](arg1);
}

export function DeleteProvider(arg1) {
  return window['go']['main']['WailsApp']['DeleteProvider'](arg1);
}

export function DetectAuthMethods() {
  return window['go']['main']['WailsApp']['DetectAuthMethods']();
}

export function DetectCLIToken(arg1) {
  return window['go']['main']['WailsApp']['DetectCLIToken'](arg1);
}

export function DetectOllama() {
  return window['go']['main']['WailsApp']['DetectOllama']();
}

export function DisableAutoRefresh(arg1) {
  return window['go']['main']['WailsApp']['DisableAutoRefresh'](arg1);
}

export function DownloadUpdate(arg1) {
  return window['go']['main']['WailsApp']['DownloadUpdate'](arg1);
}

export function EnableAutoRefresh(arg1) {
  return window['go']['main']['WailsApp']['EnableAutoRefresh'](arg1);
}

export function EnsureOllamaAndSmolLM2() {
  return window['go']['main']['WailsApp']['EnsureOllamaAndSmolLM2']();
}

export function GenerateTitle(arg1, arg2) {
  return window['go']['main']['WailsApp']['GenerateTitle'](arg1, arg2);
}

export function GetConversationMessages(arg1) {
  return window['go']['main']['WailsApp']['GetConversationMessages'](arg1);
}

export function GetConversations() {
  return window['go']['main']['WailsApp']['GetConversations']();
}

export function GetDisclaimerStatus() {
  return window['go']['main']['WailsApp']['GetDisclaimerStatus']();
}

export function GetModels() {
  return window['go']['main']['WailsApp']['GetModels']();
}

export function GetOAuthDeviceFlowProviders() {
  return window['go']['main']['WailsApp']['GetOAuthDeviceFlowProviders']();
}

export function GetOAuthDeviceFlowStatus(arg1) {
  return window['go']['main']['WailsApp']['GetOAuthDeviceFlowStatus'](arg1);
}

export function GetProviderHealthStatus(arg1) {
  return window['go']['main']['WailsApp']['GetProviderHealthStatus'](arg1);
}

export function GetUpdateSettings() {
  return window['go']['main']['WailsApp']['GetUpdateSettings']();
}

export function GetVersion() {
  return window['go']['main']['WailsApp']['GetVersion']();
}

export function GetVersionNotes() {
  return window['go']['main']['WailsApp']['GetVersionNotes']();
}

export function GetMemories(arg1, arg2) {
  return window['go']['main']['WailsApp']['GetMemories'](arg1, arg2);
}

export function GetMemoryByID(arg1) {
  return window['go']['main']['WailsApp']['GetMemoryByID'](arg1);
}

export function DeleteMemory(arg1) {
  return window['go']['main']['WailsApp']['DeleteMemory'](arg1);
}

export function SearchMemories(arg1) {
  return window['go']['main']['WailsApp']['SearchMemories'](arg1);
}

export function GetPendingReviews(arg1, arg2) {
  return window['go']['main']['WailsApp']['GetPendingReviews'](arg1, arg2);
}

export function ApproveFact(arg1) {
  return window['go']['main']['WailsApp']['ApproveFact'](arg1);
}

export function RejectFact(arg1) {
  return window['go']['main']['WailsApp']['RejectFact'](arg1);
}

export function GetMemoryStats() {
  return window['go']['main']['WailsApp']['GetMemoryStats']();
}

export function GetMemoriesBySession(arg1) {
  return window['go']['main']['WailsApp']['GetMemoriesBySession'](arg1);
}

export function SetMemoryInjectionEnabled(arg1) {
  return window['go']['main']['WailsApp']['SetMemoryInjectionEnabled'](arg1);
}

export function SetSessionMemoryInjection(arg1, arg2) {
  return window['go']['main']['WailsApp']['SetSessionMemoryInjection'](arg1, arg2);
}

export function HardDeleteConversation(arg1) {
  return window['go']['main']['WailsApp']['HardDeleteConversation'](arg1);
}

export function HasAPIKey(arg1) {
  return window['go']['main']['WailsApp']['HasAPIKey'](arg1);
}

export function ListProviders() {
  return window['go']['main']['WailsApp']['ListProviders']();
}

export function OpenDownloadURL(arg1) {
  return window['go']['main']['WailsApp']['OpenDownloadURL'](arg1);
}

export function OpenGitHubIssue(arg1, arg2) {
  return window['go']['main']['WailsApp']['OpenGitHubIssue'](arg1, arg2);
}

export function ParseServiceAccountJSON(arg1) {
  return window['go']['main']['WailsApp']['ParseServiceAccountJSON'](arg1);
}

export function PullOllamaModel(arg1) {
  return window['go']['main']['WailsApp']['PullOllamaModel'](arg1);
}

export function RefreshToken(arg1) {
  return window['go']['main']['WailsApp']['RefreshToken'](arg1);
}

export function ReportComplianceFeedback(arg1, arg2) {
  return window['go']['main']['WailsApp']['ReportComplianceFeedback'](arg1, arg2);
}

export function RestoreConversation(arg1) {
  return window['go']['main']['WailsApp']['RestoreConversation'](arg1);
}

export function SaveAPIKey(arg1, arg2) {
  return window['go']['main']['WailsApp']['SaveAPIKey'](arg1, arg2);
}

export function SendMessage(arg1) {
  return window['go']['main']['WailsApp']['SendMessage'](arg1);
}

export function SendMessageStream(arg1) {
  return window['go']['main']['WailsApp']['SendMessageStream'](arg1);
}

export function SetUpdateSettings(arg1) {
  return window['go']['main']['WailsApp']['SetUpdateSettings'](arg1);
}

export function ShowEmergencyDialog(arg1, arg2) {
  return window['go']['main']['WailsApp']['ShowEmergencyDialog'](arg1, arg2);
}

export function SkipUpdateVersion(arg1) {
  return window['go']['main']['WailsApp']['SkipUpdateVersion'](arg1);
}

export function StartOAuthDeviceFlow(arg1) {
  return window['go']['main']['WailsApp']['StartOAuthDeviceFlow'](arg1);
}

export function StartOllamaServer() {
  return window['go']['main']['WailsApp']['StartOllamaServer']();
}

export function StopGeneration() {
  return window['go']['main']['WailsApp']['StopGeneration']();
}

export function TestAPIKey(arg1, arg2, arg3) {
  return window['go']['main']['WailsApp']['TestAPIKey'](arg1, arg2, arg3);
}

export function UpdateProvider(arg1) {
  return window['go']['main']['WailsApp']['UpdateProvider'](arg1);
}
