// @ts-check
// Caution: this file type should not be changed manually. It is generated by Wails CLI.

export function SendMessage(arg1) {
  return window['go']['main']['WailsApp']['SendMessage'](arg1);
}

export function SendMessageStream(arg1) {
  return window['go']['main']['WailsApp']['SendMessageStream'](arg1);
}

export function StopGeneration() {
  return window['go']['main']['WailsApp']['StopGeneration']();
}

export function GetConversations() {
  return window['go']['main']['WailsApp']['GetConversations']();
}

export function CreateConversation() {
  return window['go']['main']['WailsApp']['CreateConversation']();
}

export function GetModels() {
  return window['go']['main']['WailsApp']['GetModels']();
}

export function CheckEmergency(arg1) {
  return window['go']['main']['WailsApp']['CheckEmergency'](arg1);
}

export function GenerateTitle(arg1, arg2) {
  return window['go']['main']['WailsApp']['GenerateTitle'](arg1, arg2);
}

export function ShowEmergencyDialog(arg1, arg2) {
  return window['go']['main']['WailsApp']['ShowEmergencyDialog'](arg1, arg2);
}

export function GetDisclaimerStatus() {
  return window['go']['main']['WailsApp']['GetDisclaimerStatus']();
}

export function AcceptDisclaimer(arg1) {
  return window['go']['main']['WailsApp']['AcceptDisclaimer'](arg1);
}

export function DeclineDisclaimer() {
  return window['go']['main']['WailsApp']['DeclineDisclaimer']();
}

export function ReportComplianceFeedback(arg1, arg2) {
  return window['go']['main']['WailsApp']['ReportComplianceFeedback'](arg1, arg2);
}
