// Caution: this file type should not be changed manually. It is generated by Wails CLI.

export interface SendMessageRequest {
  conversation_id: string;
  messages: Array<{ role: string; content: string }>;
  model: string;
}

export interface SendMessageResponse {
  reply: string;
  confidence: number;
  warnings: Array<string>;
}

export interface ConversationSummary {
  id: string;
  title: string;
  updated_at: string;
}

export interface ModelInfo {
  id: string;
  name: string;
  provider: string;
}

export interface EmergencyResult {
  level: string;
  message: string;
  action: string;
}

export interface DisclaimerStatus {
  required: boolean;
  text: string;
  version: string;
}

export function SendMessage(arg1: SendMessageRequest): Promise<SendMessageResponse>;

export function SendMessageStream(arg1: SendMessageRequest): Promise<void>;

export function StopGeneration(): Promise<void>;

export function GetConversations(): Promise<Array<ConversationSummary>>;

export function CreateConversation(): Promise<string>;

export function GetModels(): Promise<Array<ModelInfo>>;

export function CheckEmergency(arg1: string): Promise<EmergencyResult>;

export function GenerateTitle(arg1: string, arg2: string): Promise<void>;

export function ShowEmergencyDialog(arg1: string, arg2: string): Promise<void>;

export function GetDisclaimerStatus(): Promise<DisclaimerStatus>;

export function AcceptDisclaimer(arg1: string): Promise<void>;

export function DeclineDisclaimer(): Promise<void>;

export function ReportComplianceFeedback(arg1: string, arg2: string): Promise<void>;

export interface UpdateInfoResponse {
  version: string;
  name: string;
  body: string;
  published_at: string;
  mandatory: boolean;
  channel: string;
}

export interface DownloadUpdateRequest {
  version: string;
}

export interface UpdateSettingsResponse {
  check_enabled: boolean;
  channel: string;
  skip_version: string;
}

export function CheckUpdate(): Promise<UpdateInfoResponse | null>;

export function DownloadUpdate(arg1: DownloadUpdateRequest): Promise<string>;

export function ApplyUpdate(arg1: string): Promise<void>;

export function GetUpdateSettings(): Promise<UpdateSettingsResponse>;

export function SetUpdateSettings(arg1: UpdateSettingsResponse): Promise<void>;

export function SkipUpdateVersion(arg1: string): Promise<void>;

export function OpenDownloadURL(arg1: string): void;

export function SaveAPIKey(arg1: string, arg2: string): Promise<void>;

export function HasAPIKey(arg1: string): Promise<boolean>;

export function GetVersion(): Promise<string>;

export interface CLIDetectResult {
  provider_type: string;
  detected: boolean;
  credential_path: string;
  logged_in: boolean;
  error: string;
}

export function DetectCLIToken(arg1: string): Promise<CLIDetectResult>;

export function BuildCLIProvider(arg1: string, arg2: string): Promise<ProviderConfig>;
