// @ts-check
// Caution: this file type should not be changed manually. It is generated by Wails CLI.

export function SendMessage(arg1) {
  return window['go']['main']['WailsApp']['SendMessage'](arg1);
}

export function SendMessageStream(arg1) {
  return window['go']['main']['WailsApp']['SendMessageStream'](arg1);
}

export function StopGeneration() {
  return window['go']['main']['WailsApp']['StopGeneration']();
}

export function GetConversations() {
  return window['go']['main']['WailsApp']['GetConversations']();
}

export function CreateConversation() {
  return window['go']['main']['WailsApp']['CreateConversation']();
}

export function GetModels() {
  return window['go']['main']['WailsApp']['GetModels']();
}

export function CheckEmergency(arg1) {
  return window['go']['main']['WailsApp']['CheckEmergency'](arg1);
}

export function GenerateTitle(arg1, arg2) {
  return window['go']['main']['WailsApp']['GenerateTitle'](arg1, arg2);
}

export function ShowEmergencyDialog(arg1, arg2) {
  return window['go']['main']['WailsApp']['ShowEmergencyDialog'](arg1, arg2);
}

export function GetDisclaimerStatus() {
  return window['go']['main']['WailsApp']['GetDisclaimerStatus']();
}

export function AcceptDisclaimer(arg1) {
  return window['go']['main']['WailsApp']['AcceptDisclaimer'](arg1);
}

export function DeclineDisclaimer() {
  return window['go']['main']['WailsApp']['DeclineDisclaimer']();
}

export function ReportComplianceFeedback(arg1, arg2) {
  return window['go']['main']['WailsApp']['ReportComplianceFeedback'](arg1, arg2);
}

export function CheckUpdate() {
  return window['go']['main']['WailsApp']['CheckUpdate']();
}

export function DownloadUpdate(arg1) {
  return window['go']['main']['WailsApp']['DownloadUpdate'](arg1);
}

export function ApplyUpdate(arg1) {
  return window['go']['main']['WailsApp']['ApplyUpdate'](arg1);
}

export function GetUpdateSettings() {
  return window['go']['main']['WailsApp']['GetUpdateSettings']();
}

export function SetUpdateSettings(arg1) {
  return window['go']['main']['WailsApp']['SetUpdateSettings'](arg1);
}

export function SkipUpdateVersion(arg1) {
  return window['go']['main']['WailsApp']['SkipUpdateVersion'](arg1);
}

export function OpenDownloadURL(arg1) {
  window['go']['main']['WailsApp']['OpenDownloadURL'](arg1);
}

export function SaveAPIKey(arg1, arg2) {
  return window['go']['main']['WailsApp']['SaveAPIKey'](arg1, arg2);
}

export function HasAPIKey(arg1) {
  return window['go']['main']['WailsApp']['HasAPIKey'](arg1);
}

export function GetVersion() {
  return window['go']['main']['WailsApp']['GetVersion']();
}

export function DetectCLIToken(arg1) {
  return window['go']['main']['WailsApp']['DetectCLIToken'](arg1);
}

export function BuildCLIProvider(arg1, arg2) {
  return window['go']['main']['WailsApp']['BuildCLIProvider'](arg1, arg2);
}

export function RefreshToken(arg1) {
  return window['go']['main']['WailsApp']['RefreshToken'](arg1);
}

export function EnableAutoRefresh(arg1) {
  return window['go']['main']['WailsApp']['EnableAutoRefresh'](arg1);
}

export function DisableAutoRefresh(arg1) {
  return window['go']['main']['WailsApp']['DisableAutoRefresh'](arg1);
}
