// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {main} from '../models';
import {auth} from '../models';
import {entity} from '../models';
import {feedback} from '../models';

export function AcceptDisclaimer(arg1:string):Promise<void>;

export function ApplyUpdate(arg1:string):Promise<void>;

export function BuildCLIProvider(arg1:string,arg2:string):Promise<models.ProviderConfig>;

export function CancelOAuthDeviceFlow(arg1:string):Promise<void>;

export function CollectSystemInfo():Promise<feedback.SystemInfo>;

export function CheckEmergency(arg1:string):Promise<main.EmergencyResult>;

export function CheckProviderHealth(arg1:string):Promise<main.HealthResultResponse>;

export function CheckUpdate():Promise<main.UpdateInfoResponse>;

export function CreateConversation():Promise<string>;

export function CreateOllamaProvider():Promise<models.ProviderConfig>;

export function CreateProvider(arg1:models.ProviderConfig):Promise<void>;

export function DeclineDisclaimer():Promise<void>;

export function DeleteConversation(arg1:string):Promise<void>;

export function DeleteProvider(arg1:string):Promise<void>;

export function DetectAuthMethods():Promise<main.AuthDetectResult>;

export function DetectCLIToken(arg1:string):Promise<auth.CLIDetectResult>;

export function DetectOllama():Promise<main.OllamaDetectResult>;

export function DisableAutoRefresh(arg1:string):Promise<void>;

export function DownloadUpdate(arg1:main.DownloadUpdateRequest):Promise<string>;

export function EnableAutoRefresh(arg1:string):Promise<void>;

export function EnsureOllamaAndSmolLM2():Promise<main.OllamaDetectResult>;

export function GenerateTitle(arg1:string,arg2:string):Promise<void>;

export function GetConversationMessages(arg1:string):Promise<Array<main.MessageResponse>>;

export function GetConversations():Promise<Array<main.ConversationSummary>>;

export function GetDisclaimerStatus():Promise<main.DisclaimerStatus>;

export function GetModels():Promise<Array<main.ModelInfo>>;

export function GetOAuthDeviceFlowProviders():Promise<Array<main.OAuthDeviceFlowProviderInfo>>;

export function GetOAuthDeviceFlowStatus(arg1:string):Promise<main.DeviceFlowStatusResponse>;

export function GetProviderHealthStatus(arg1:string):Promise<main.HealthResultResponse>;

export function GetUpdateSettings():Promise<main.UpdateSettingsResponse>;

export function GetVersion():Promise<string>;

export function GetVersionNotes():Promise<Array<entity.VersionNote>>;

export function GetMemories(arg1:number,arg2:number):Promise<Array<main.MemoryItem>>;

export function GetMemoryByID(arg1:string):Promise<main.MemoryItem>;

export function DeleteMemory(arg1:string):Promise<void>;

export function SearchMemories(arg1:string):Promise<Array<main.MemoryItem>>;

export function GetPendingReviews(arg1:number,arg2:number):Promise<Array<main.MemoryItem>>;

export function ApproveFact(arg1:string):Promise<void>;

export function RejectFact(arg1:string):Promise<void>;

export function GetMemoryStats():Promise<main.MemoryStats>;

export function GetMemoriesBySession(arg1:string):Promise<Array<main.MemoryItem>>;

export function SetMemoryInjectionEnabled(arg1:boolean):Promise<void>;

export function SetSessionMemoryInjection(arg1:string,arg2:boolean):Promise<void>;

export function HardDeleteConversation(arg1:string):Promise<void>;

export function HasAPIKey(arg1:string):Promise<boolean>;

export function ListProviders():Promise<Array<models.ProviderConfig>>;

export function OpenDownloadURL(arg1:string):Promise<void>;

export function OpenGitHubIssue(arg1:string,arg2:string):Promise<void>;

export function ParseServiceAccountJSON(arg1:string):Promise<Record<string, string>>;

export function PullOllamaModel(arg1:string):Promise<void>;

export function RefreshToken(arg1:string):Promise<void>;

export function ReportComplianceFeedback(arg1:string,arg2:string):Promise<void>;

export function RestoreConversation(arg1:string):Promise<void>;

export function SaveAPIKey(arg1:string,arg2:string):Promise<void>;

export function SendMessage(arg1:main.SendMessageRequest):Promise<main.SendMessageResponse>;

export function SendMessageStream(arg1:main.SendMessageRequest):Promise<void>;

export function SetUpdateSettings(arg1:main.UpdateSettingsResponse):Promise<void>;

export function ShowEmergencyDialog(arg1:string,arg2:string):Promise<void>;

export function SkipUpdateVersion(arg1:string):Promise<void>;

export function StartOAuthDeviceFlow(arg1:string):Promise<main.DeviceFlowStartResponse>;

export function StartOllamaServer():Promise<void>;

export function StopGeneration():Promise<void>;

export function TestAPIKey(arg1:string,arg2:string,arg3:string):Promise<main.TestAPIKeyResult>;

export function UpdateProvider(arg1:models.ProviderConfig):Promise<void>;
