// generate-api-docs.go 从源码生成 API 文档 Markdown 到 docs/api/_generated/。
//
// 生成内容：
//   - core-types.md：pkg/models 中的共享类型（struct / enum / alias）。
//   - ports.md：internal/application/port 中的接口契约。
//   - bindings.md：wails_app_*.go 中暴露给前端的 Wails 绑定方法。
//
// 用法：go run scripts/api-docs/generate-api-docs.go
package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	outputDir = "docs/api/_generated"
	repoRoot  = "."
)

func main() {
	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		fail("create output dir: %v", err)
	}

	if err := generateCoreTypes(); err != nil {
		fail("generate core types: %v", err)
	}
	if err := generatePorts(); err != nil {
		fail("generate ports: %v", err)
	}
	if err := generateBindings(); err != nil {
		fail("generate bindings: %v", err)
	}
}

func fail(format string, args ...interface{}) {
	fmt.Fprintf(os.Stderr, "error: "+format+"\n", args...)
	os.Exit(1)
}

// ==================== core-types.md ====================

func generateCoreTypes() error {
	files, err := collectGoFiles(filepath.Join(repoRoot, "pkg/models"))
	if err != nil {
		return err
	}

	var types []typeInfo
	var consts []constInfo
	for _, path := range files {
		fset := token.NewFileSet()
		f, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if err != nil {
			return fmt.Errorf("parse %s: %w", path, err)
		}
		for _, decl := range f.Decls {
			switch d := decl.(type) {
			case *ast.GenDecl:
				if d.Tok == token.TYPE {
					for _, spec := range d.Specs {
						ts := spec.(*ast.TypeSpec)
						types = append(types, parseTypeSpec(ts, d.Doc))
					}
				} else if d.Tok == token.CONST {
					consts = append(consts, parseConstBlock(d)...)
				}
			}
		}
	}

	sort.Slice(types, func(i, j int) bool { return types[i].Name < types[j].Name })

	var b strings.Builder
	b.WriteString("# Core API Types\n\n")
	b.WriteString("> ⚙️ **Auto-generated from `pkg/models/*.go`.**\n")
	b.WriteString("> Do not edit this file manually; run `make docs` to regenerate.\n\n")
	b.WriteString("Shared data structures used by Wails bindings and internal interfaces.\n\n")

	for _, t := range types {
		writeTypeSection(&b, t, consts)
	}

	return os.WriteFile(filepath.Join(outputDir, "core-types.md"), []byte(b.String()), 0o644)
}

type typeInfo struct {
	Name        string
	Doc         string
	Kind        string // struct, alias, interface
	Underlying  string
	Fields      []fieldInfo
	EnumConsts  []constInfo
}

type fieldInfo struct {
	Name     string
	Type     string
	JSONTag  string
	Doc      string
}

type constInfo struct {
	Name  string
	Value string
	Type  string
	Doc   string
}

func parseTypeSpec(ts *ast.TypeSpec, doc *ast.CommentGroup) typeInfo {
	info := typeInfo{Name: ts.Name.Name, Doc: commentText(doc)}
	switch t := ts.Type.(type) {
	case *ast.StructType:
		info.Kind = "struct"
		for _, f := range t.Fields.List {
			for _, name := range f.Names {
				fi := fieldInfo{
					Name: name.Name,
					Type: typeString(f.Type),
					Doc:  commentText(f.Doc),
				}
				if f.Tag != nil {
					fi.JSONTag = extractJSONTag(f.Tag.Value)
				}
				info.Fields = append(info.Fields, fi)
			}
		}
	case *ast.Ident:
		info.Kind = "alias"
		info.Underlying = t.Name
	case *ast.InterfaceType:
		info.Kind = "interface"
	default:
		info.Kind = "alias"
		info.Underlying = typeString(ts.Type)
	}
	return info
}

func parseConstBlock(d *ast.GenDecl) []constInfo {
	var out []constInfo
	for _, spec := range d.Specs {
		vs := spec.(*ast.ValueSpec)
		typ := ""
		if vs.Type != nil {
			typ = typeString(vs.Type)
		}
		for i, name := range vs.Names {
			val := ""
			if i < len(vs.Values) && vs.Values[i] != nil {
				val = exprString(vs.Values[i])
			}
			out = append(out, constInfo{
				Name:  name.Name,
				Value: val,
				Type:  typ,
				Doc:   commentText(vs.Doc),
			})
		}
	}
	return out
}

func writeTypeSection(b *strings.Builder, t typeInfo, allConsts []constInfo) {
	b.WriteString(fmt.Sprintf("## `%s`\n\n", t.Name))
	if t.Doc != "" {
		b.WriteString(t.Doc + "\n\n")
	}

	switch t.Kind {
	case "struct":
		if len(t.Fields) == 0 {
			b.WriteString("*No exported fields.*\n\n")
			return
		}
		b.WriteString("| Field | Type | JSON | Description |\n")
		b.WriteString("|-------|------|------|-------------|\n")
		for _, f := range t.Fields {
			jsonCol := "—"
			if f.JSONTag != "" {
				jsonCol = "`" + f.JSONTag + "`"
			}
			desc := f.Doc
			if desc == "" {
				desc = "—"
			}
			b.WriteString(fmt.Sprintf("| `%s` | `%s` | %s | %s |\n", f.Name, f.Type, jsonCol, desc))
		}
		b.WriteString("\n")
	case "alias":
		b.WriteString(fmt.Sprintf("- **Type**: `%s`\n\n", t.Underlying))
		// 查找该类型的枚举常量
		var enums []constInfo
		for _, c := range allConsts {
			if c.Type == t.Name {
				enums = append(enums, c)
			}
		}
		if len(enums) > 0 {
			b.WriteString("| Constant | Value | Description |\n")
			b.WriteString("|----------|-------|-------------|\n")
			for _, c := range enums {
				desc := c.Doc
				if desc == "" {
					desc = "—"
				}
				b.WriteString(fmt.Sprintf("| `%s` | %s | %s |\n", c.Name, c.Value, desc))
			}
			b.WriteString("\n")
		}
	case "interface":
		b.WriteString("*Interface type; see source for method definitions.*\n\n")
	}
}

// ==================== ports.md ====================

type portInfo struct {
	Name    string
	Doc     string
	Methods []methodInfo
}

type methodInfo struct {
	Name    string
	Sig     string
	Doc     string
}

func generatePorts() error {
	files, err := collectGoFiles(filepath.Join(repoRoot, "internal/application/port"))
	if err != nil {
		return err
	}

	var ports []portInfo
	for _, path := range files {
		fset := token.NewFileSet()
		f, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if err != nil {
			return fmt.Errorf("parse %s: %w", path, err)
		}
		for _, decl := range f.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.TYPE {
				continue
			}
			for _, spec := range gd.Specs {
				ts := spec.(*ast.TypeSpec)
				it, ok := ts.Type.(*ast.InterfaceType)
				if !ok {
					continue
				}
				p := portInfo{
					Name: ts.Name.Name,
					Doc:  commentText(gd.Doc),
				}
				for _, method := range it.Methods.List {
					ft, ok := method.Type.(*ast.FuncType)
					if !ok {
						// 跳过嵌入接口（如 NERDetector）
						continue
					}
					sig := methodSignature(method.Names[0].Name, ft)
					p.Methods = append(p.Methods, methodInfo{
						Name: method.Names[0].Name,
						Sig:  sig,
						Doc:  commentText(method.Doc),
					})
				}
				ports = append(ports, p)
			}
		}
	}

	sort.Slice(ports, func(i, j int) bool { return ports[i].Name < ports[j].Name })

	var b strings.Builder
	b.WriteString("# Application Ports\n\n")
	b.WriteString("> ⚙️ **Auto-generated from `internal/application/port/*.go`.**\n")
	b.WriteString("> Do not edit this file manually; run `make docs` to regenerate.\n\n")
	b.WriteString("Interfaces declared by the application layer and implemented by adapters.\n\n")

	for _, p := range ports {
		b.WriteString(fmt.Sprintf("## `%s`\n\n", p.Name))
		if p.Doc != "" {
			b.WriteString(p.Doc + "\n\n")
		}
		if len(p.Methods) == 0 {
			b.WriteString("*No methods.*\n\n")
			continue
		}
		b.WriteString("| Method | Signature | Description |\n")
		b.WriteString("|--------|-----------|-------------|\n")
		for _, m := range p.Methods {
			desc := m.Doc
			if desc == "" {
				desc = "—"
			}
			b.WriteString(fmt.Sprintf("| `%s` | `%s` | %s |\n", m.Name, m.Sig, desc))
		}
		b.WriteString("\n")
	}

	return os.WriteFile(filepath.Join(outputDir, "ports.md"), []byte(b.String()), 0o644)
}

// ==================== bindings.md ====================

func generateBindings() error {
	files, err := collectBindingFiles(filepath.Join(repoRoot, "wails_app_*.go"))
	if err != nil {
		return err
	}

	var sections []bindingSection
	for _, path := range files {
		fset := token.NewFileSet()
		f, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if err != nil {
			return fmt.Errorf("parse %s: %w", path, err)
		}
		sec := bindingSection{Name: filepath.Base(path)}
		for _, decl := range f.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if !ok || fn.Recv == nil || len(fn.Recv.List) == 0 {
				continue
			}
			recvType := typeString(fn.Recv.List[0].Type)
			if !strings.Contains(recvType, "WailsApp") {
				continue
			}
			if !ast.IsExported(fn.Name.Name) {
				continue
			}
			sec.Methods = append(sec.Methods, methodInfo{
				Name: fn.Name.Name,
				Sig:  funcSignature(fn.Type),
				Doc:  commentText(fn.Doc),
			})
		}
		if len(sec.Methods) > 0 {
			sections = append(sections, sec)
		}
	}

	sort.Slice(sections, func(i, j int) bool { return sections[i].Name < sections[j].Name })
	for i := range sections {
		sort.Slice(sections[i].Methods, func(a, b int) bool {
			return sections[i].Methods[a].Name < sections[i].Methods[b].Name
		})
	}

	var b strings.Builder
	b.WriteString("# Wails Frontend-Backend Bindings\n\n")
	b.WriteString("> ⚙️ **Auto-generated from `wails_app_*.go`.**\n")
	b.WriteString("> Do not edit this file manually; run `make docs` to regenerate.\n\n")
	b.WriteString("Public methods exposed by `WailsApp` and callable from the frontend via `window.go.main.WailsApp`.\n\n")

	for _, sec := range sections {
		b.WriteString(fmt.Sprintf("## `%s`\n\n", sec.Name))
		b.WriteString("| Method | Signature | Description |\n")
		b.WriteString("|--------|-----------|-------------|\n")
		for _, m := range sec.Methods {
			desc := m.Doc
			if desc == "" {
				desc = "—"
			}
			b.WriteString(fmt.Sprintf("| `%s` | `%s` | %s |\n", m.Name, m.Sig, desc))
		}
		b.WriteString("\n")
	}

	return os.WriteFile(filepath.Join(outputDir, "bindings.md"), []byte(b.String()), 0o644)
}

type bindingSection struct {
	Name    string
	Methods []methodInfo
}

// ==================== helpers ====================

func collectGoFiles(dir string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	var out []string
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		if !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		out = append(out, filepath.Join(dir, name))
	}
	sort.Strings(out)
	return out, nil
}

func collectBindingFiles(pattern string) ([]string, error) {
	matches, err := filepath.Glob(pattern)
	if err != nil {
		return nil, err
	}
	var out []string
	for _, m := range matches {
		if strings.HasSuffix(m, "_test.go") {
			continue
		}
		out = append(out, m)
	}
	sort.Strings(out)
	return out, nil
}

func commentText(cg *ast.CommentGroup) string {
	if cg == nil {
		return ""
	}
	lines := make([]string, 0, len(cg.List))
	for _, c := range cg.List {
		text := strings.TrimPrefix(c.Text, "//")
		text = strings.TrimPrefix(text, " ")
		lines = append(lines, text)
	}
	return strings.Join(lines, " ")
}

func typeString(expr ast.Expr) string {
	switch e := expr.(type) {
	case *ast.Ident:
		return e.Name
	case *ast.StarExpr:
		return "*" + typeString(e.X)
	case *ast.ArrayType:
		if e.Len == nil {
			return "[]" + typeString(e.Elt)
		}
		return "[" + exprString(e.Len) + "]" + typeString(e.Elt)
	case *ast.MapType:
		return "map[" + typeString(e.Key) + "]" + typeString(e.Value)
	case *ast.SelectorExpr:
		return typeString(e.X) + "." + e.Sel.Name
	case *ast.InterfaceType:
		return "interface{}"
	case *ast.FuncType:
		return "func" + funcParams(e.Params) + funcResults(e.Results)
	case *ast.ChanType:
		return "chan " + typeString(e.Value)
	case *ast.BasicLit:
		return e.Value
	case *ast.Ellipsis:
		return "..." + typeString(e.Elt)
	case *ast.ParenExpr:
		return "(" + typeString(e.X) + ")"
	case *ast.IndexExpr:
		return typeString(e.X) + "[" + typeString(e.Index) + "]"
	case *ast.IndexListExpr:
		var indices []string
		for _, idx := range e.Indices {
			indices = append(indices, typeString(idx))
		}
		return typeString(e.X) + "[" + strings.Join(indices, ", ") + "]"
	default:
		return fmt.Sprintf("%T", expr)
	}
}

func exprString(expr ast.Expr) string {
	switch e := expr.(type) {
	case *ast.BasicLit:
		return e.Value
	case *ast.Ident:
		return e.Name
	case *ast.SelectorExpr:
		return exprString(e.X) + "." + e.Sel.Name
	case *ast.BinaryExpr:
		return exprString(e.X) + " " + e.Op.String() + " " + exprString(e.Y)
	case *ast.UnaryExpr:
		return e.Op.String() + exprString(e.X)
	default:
		return typeString(e)
	}
}

func extractJSONTag(tag string) string {
	// tag 形如 `json:"field,omitempty"`
	tag = strings.Trim(tag, "`")
	for _, part := range strings.Split(tag, " ") {
		if strings.HasPrefix(part, "json:\"") {
			inner := strings.TrimPrefix(part, "json:\"")
			inner = strings.TrimSuffix(inner, "\"")
			return strings.Split(inner, ",")[0]
		}
	}
	return ""
}

func methodSignature(name string, ft *ast.FuncType) string {
	return name + funcParams(ft.Params) + funcResults(ft.Results)
}

func funcSignature(ft *ast.FuncType) string {
	return funcParams(ft.Params) + funcResults(ft.Results)
}

func funcParams(fields *ast.FieldList) string {
	if fields == nil {
		return "()"
	}
	var parts []string
	for _, f := range fields.List {
		t := typeString(f.Type)
		if len(f.Names) == 0 {
			parts = append(parts, t)
			continue
		}
		for _, n := range f.Names {
			parts = append(parts, n.Name+" "+t)
		}
	}
	return "(" + strings.Join(parts, ", ") + ")"
}

func funcResults(fields *ast.FieldList) string {
	if fields == nil {
		return ""
	}
	var parts []string
	for _, f := range fields.List {
		if len(f.Names) == 0 {
			parts = append(parts, typeString(f.Type))
		} else {
			var names []string
			for _, n := range f.Names {
				names = append(names, n.Name)
			}
			parts = append(parts, strings.Join(names, ", ")+" "+typeString(f.Type))
		}
	}
	if len(parts) == 1 {
		return " " + parts[0]
	}
	return " (" + strings.Join(parts, ", ") + ")"
}
